### ISSUE TITLE
grow filesystem

### ISSUE THREAD

**Issue by clkao** [nlf/dlite#109]
There should be a simple command growing filesystem.

This can be done manually with:

```
# append 10g to disk
% dlite stop
% dd if=/dev/zero bs=1m count=10000 >> ~/.dlite/disk.img
% dlite start
# login and resize partition
% ssh docker@$(dlite ip)
$ sudo killall docker
$ sudo umount /var/lib/docker
$ sudo fdisk -u /dev/vda
fdisk> delete partition 1
fdisk> create new partion 1 as primary with max size
fdisk> w
% dlite stop
% dlite start
# login and resize btrfs
% ssh docker@$(dlite ip) sudo btrfs filesystem resize max /var/lib/docker
```

viola!

**Comment by nlf** [comment]
i like this idea.. i'll have to figure out the best way to implement it since it requires changes in both dlite and dhyveos

**Comment by clkao** [comment]
Looking at the current init script hook, it seems we can do very similar thing to the magic check by having a /var/dhyveos_desired_disksize file, and just have S03automount do the growing, rm that desired disksize file, and reboot.

**Comment by supersophie** [comment]
I did try these commands, because I accidentally created my vm with 1Gb...

Commands did not work for me: 
$ sudo btrfs filesystem resize max /var/lib/docker
Resize '/var/lib/docker' of 'max'
ERROR: unable to resize '/var/lib/docker' - Invalid argument

$ mount /var/lib/docker
mount: can't find /var/lib/docker in /etc/fstab
Explains why not.

Is there a recommended way to delete and start again with a new VM?

**Comment by nlf** [comment]
you can just run `dlite rebuild` and it will make a new disk image, the `-d` flag works to specify the size.

``` shell
dlite stop
dlite rebuild -d 20
dlite start
```

would rebuild the disk with a 20gb image

**Comment by supersophie** [comment]
thanks. Just did this.

それでは、また。Sophie

**Comment by nlf** [comment]
this actually isn't going to happen because i'm refactoring things to use a sparse disk image instead, the rebuild command is sufficient i think. closing for now.
