### ISSUE TITLE
Implement fuse filesystem

### ISSUE THREAD

**Issue by nlf** [nlf/dlite#146]
depends on #145 

this will let us have total control over uid/gid mapping and hopefully increase performance a bit

**Comment by elliottsj** [comment]
@nlf Have you seen [bindfs](http://bindfs.org/)? I've had success using it with Vagrant NFS-synced folders via [vagrant-bindfs](https://github.com/gael-ian/vagrant-bindfs)).

e.g. with Vagrant, you could share your host's `/Users` to `/Users.nfs` on the VM, then use bindfs on the VM to bind `/Users.nfs` to `/Users` with custom permissions. Files in `/Users.nfs` show up as `501:dialout`, but files in `/Users` will appear with custom permissions, e.g. `--force-user=ubuntu --force-group=ubuntu` will cause permissions to be `ubuntu:ubuntu`.

I'm not too sure if/how bindfs can work on DhyveOS or if it resolves all of the issues raised in #50, https://github.com/nlf/dlite/commit/ad08a421b45ce795e402c7c3213d0f95b96404fe, & #135, but I thought I'd mention it since no one else has :grin:

**Comment by nlf** [comment]
i may be backing out on this. performance with FUSE filesystems in the VM is just absolutely abysmal. every bit as slow as 9p (which is also incredibly slow). note that bindfs is a FUSE filesystem as well and suffers from the same horrible performance issues.

we may end up sticking with NFS and the `-maproot` option since it comes the closest to "correct" behavior.

the only major issue with this solution is that files that are chowned within the vm or a container will end up with invalid uid/gid on the host. unfortunately, i haven't yet come up with a way to get around that, though i do have a couple of ideas involving ACLs on the host.

**Comment by nlf** [comment]
after some continued evaluation we're definitely reverting back to NFS for the file share and i'll simply incorporate some workarounds for the bigger issues (inotify and permissions). there will always be a cosmetic issue in that files on the host that were chowned from the vm or container will display invalid uid/gid from the host's perspective. it will be purely cosmetic though since i have some ideas to make sure your user still has permission to these files.

**Comment by TomFrost** [comment]
Floored about this approach-- thanks for the update!
