### ISSUE TITLE
Can't forward SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by sowawa** [nlf/dlite#156]
I'd like to do like this: https://github.com/docker/docker/issues/6396
We can't forward SSH_AUTH_SOCK because use nfs... :cry: 
Do you have any idea for forwarding SSH_AUTH_SOCK to the container?

**Comment by nlf** [comment]
hmm.. forwarding a unix domain socket through FUSE (which is what i'm using for version 2) isn't technically possible as far as i'm aware. the problem is a forwarded socket isn't the same socket as the one on the host. they're not connected to each other in any way.

unfortunately unless you can make your SSH_AUTH_SOCK a tcp socket instead of a unix domain socket, this just isn't possible

**Comment by sowawa** [comment]
I got it... :cry:
I think it is only the way to use SSH_AUTH_SOCK a tcp socket instead of a unix domain socket.

But I think Dlite is very interesting and effective to use Docker in OSX. I have read other issues and I have known that you'll use FUSE in version 2. I think it is also interesting approach to use FUSE between the host and the guest for sharing filesystem.
Best wishes to you!

Thanks :bow:
