### ISSUE TITLE
How to compile dlite for docker 1.11.0?

### ISSUE THREAD

**Issue by synic** [nlf/dlite#166]
The new release is out, and I made the mistake of doing a `brew upgrade`.

Is there a way to compile dlite for the new version?

**Comment by nlf** [comment]
i'll see about getting a new build of dhyveos out for docker 1.11, give me a bit

**Comment by nlf** [comment]
v2.3.0 of dhyve-os is built and released, unfortunately i assumed i would have dlite 2 finished before the next major release of docker came out and hardcoded the os version in the 1.x releases, so in order to update to it you'll have to specify what version to update to manually (as in, the `install` and `update` commands won't find this release).

you should be able to `dlite update -v 2.3.0` though
