### ISSUE TITLE
/etc/sudoers and user-owned files

### ISSUE THREAD

**Issue by FiloSottile** [nlf/dlite#170]
Adding to sudoers a file or a path owned by the user (like any Go or Homebrew install path is most of the times) is a trivial local root vulnerability.

I would suggest turning it off by default because magic is nice, but security is more important. Most users will have the binary in an unsafe place and detecting if a place is safe is easy to get wrong.

An alternative might be to move dlite to /sbin and chowning it to root. Then dlite upgrade (with sudo) could update it.

**Comment by FiloSottile** [comment]
Also problematic: the sudoers line is not removed with uninstall.

**Comment by nlf** [comment]
the sudoers line should definitely get removed on uninstall, i agree.

i've been evaluating other solutions for this problem in general though and i haven't given up on getting things to a point that sudo isn't required at all, so i have no intention of changing the current behavior.

**Comment by FiloSottile** [comment]
I understand that it's beta, but as it is, users who run install might as well be removing the sudo password entirely.

If you are comfortable with this, please put a warning big enough that users will surely read it, that states things in those terms (most users might not make the connection between sudoers and "hey, I own this file!") to make sure that your users are comfortable with it as well.

**Comment by nlf** [comment]
i'm completely comfortable with this, for now. feel free to submit a pull request adding more text to the install prompt that explains what's being done.

btw are you on gitter by chance? we could probably discuss this stuff a lot quicker there

**Comment by nlf** [comment]
closed via #171

**Comment by FiloSottile** [comment]
For the record, the approach of changing owner and group to root and setting suid is safer and possibly easier/smoother https://github.com/zchee/docker-machine-driver-xhyve

**Comment by nlf** [comment]
the concern with suid there is that i need to know the UID of the user who is actually running the vm, since the goal here is to keep things isolated on a user level. each user on a machine should have their own vm, if you suid the dlite binary when you run it UID is effectively 0 which makes it impossible for me to know who the heck did it.

the architecture i plan to go with is move the parts of the app that require root into their own daemon, and then the client portion of things would simply communicate with that daemon via rpc. that would allow me to simply install the privileged daemon as a LaunchDaemon, and then sudo would never be required again :)
