### ISSUE TITLE
NFS support?

### ISSUE THREAD

**Issue by o5** [nlf/dlite#189]
Hi there, 

I'm trying version `2.0.0-beta5`, but NFS is probably not configured.  I think, some record should be in `/etc/exports`, or not? 

```
[~]$ ll /etc/exports
-rw-r--r--  1 root  wheel     0B May 30 15:07 /etc/exports
```

```
[~]$ dlite
DLite configuration:
  uuid           : 7aaa4359-2667-11e6-ad7c-d0a637e9cb87
  cpu count      : 4
  memory         : 2 GiB
  disk size      : 20 GiB
  hostname       : local.docker
  dns server     : 192.168.64.1
  docker version : 1.11.1

[~]$ dlite version
2.0.0-beta5
```

I'm getting `Failed to write cache file "/var/www/var/cache/dev/classes.php".` from my Symfony APP which runs in container. I fixed the same issue with project [docker-machine-nfs](https://github.com/adlogix/docker-machine-nfs) when I used Docker Toolbox / VirtualBox.

Thank you!

**Comment by nlf** [comment]
the 2.0 beta is still currently configured to use 9p for file sharing, not nfs. i'm working on reverting back, however.

your error is almost definitely because 9p doesn't report available space on a device, which symfony checks before writing files. it believes there's no space on the device so refuses to write the file.

this will be fixed after i move back to nfs

**Comment by residentsummer** [comment]
@nlf, just curios why 9p didn’t work out for dlite? I have no problems with
NFS so far, didn’t know 9P is stiil maintained either :)
