### ISSUE TITLE
Error installing on Mac OSX 10.10.4

### ISSUE THREAD

**Issue by cadu** [nlf/dlite#21]
I'm trying to install dlite on my mac but I'm getting the following error doing `sudo dlite install`:
`Building disk image: ERROR - write /Users/cadu/.dlite/disk.img: no space left on device
write /Users/cadu/.dlite/disk.img: no space left on device`

I've downloaded the binary file (1.0.4) and put it on /usr/local/bin with 755 permission and I have 14Gi free on my machine.

**Comment by nlf** [comment]
this is because the default disk size that DLite attempts to create is 30GiB which you don't have available, you can run the installer with the -d flag to specify a smaller disk size `sudo dlite install -d 10` for example would create a 10GiB disk

**Comment by cadu** [comment]
Thanks!

**Comment by supersophie** [comment]
Hi, I've tried creating a VM but had the same error when creating with either default disc size, 5g 2g and 1g. 

I have 200 Gb of free disc space available:
 $ df -lH
Filesystem                          Size   Used  Avail Capacity  iused    ifree %iused  Mounted on
/dev/disk0s2                        499G   298G   201G    60% 72919596 49008633   60%   /
localhost:/QoiQBYHdoCdzbg2H5ybSVi   499G   499G     0B   100%        0        0  100%   /Volumes/MobileBackups

$ sudo dlite install -d 1
Building disk image: ERROR!
open /Users/me/.ssh/id_rsa.pub: no such file or directory

Unsure why this looks for public key. Red herring?

**Comment by nlf** [comment]
dlite uses your public key to allow your user to ssh to the virtual machine. you can override the path by passing a flag to the install command, like `dlite install -s /path/to/your/key`

if you don't have an ssh key at all, you'll need to use ssh-keygen to make one. i'll be changing this behavior in the future so that dlite will generate its own key for you at install time rather than looking for an existing one.

**Comment by supersophie** [comment]
Key created and thanks.  Using a default key seems bad. For example I had an id_rsa for work, with .pub on works server. If I had left my .pub in ~/.ssh then the VM would have the same company public  key - If work was compromised then my VMs could be.
Glad you have considered replacing this with a custom generated key. :)

**Comment by dirn** [comment]
@supersophie that would only have been an issue if your `~/.ssh/id_rsa` were compromised. Public keys aren't an issue. That's why GitHub [publishes them](https://github.com/dirn.keys).

**Comment by supersophie** [comment]
The private and public keys for work are pushed to my servers by Puppet.  I have only the private key on my notebook.  If the servers were compromised and I had my public key on my notebook then they could SSH into my notebook, because they had the private key.  I don’t have my pub key on my notebook means they cannot access, but somebody else using a similar setup with pub key installed on notebook could then have issues.  Of course, my servers being compromised would be my primary issue to address ;)

それでは、また。Sophie

**Comment by dirn** [comment]
Ah, yes. If the private key is being pushed somewhere else, then yes. You shouldn't share private keys between machines, though.

**Comment by supersophie** [comment]
agreed. being phased out!

それでは、また。Sophie
