### ISSUE TITLE
Use docker.local not local.docker

### ISSUE THREAD

**Issue by djui** [nlf/dlite#35]
Chrome for example does not understand `local.docker:8080` (only `http://docker.local:8080`) while `docker.local:8080` is perfectly fine.

It's also more of a convention on OSX.

**Comment by leipert** [comment]
Please see issue #19

**Comment by nlf** [comment]
what do you mean by "does not understand"? i type "local.docker:8000" and the like into chrome all the time and it works just fine.

regardless, #19 is the correct solution here so i'm going to close this issue

**Comment by ruimarinho** [comment]
Just wanted to add that `.local` has had its fair share of trouble on OSX (several bugs, slow lookups), so it would be best to avoid it.

**Comment by leipert** [comment]
@ruimarinho. Interesting, do you know why it is slower? Is it because of Bonjour?
And if so, dlite adds an entry to `/etc/hosts`, so maybe a Bonjour lookup takes no time...

However regarding the original problem. You can use `--hostname foo.example` or `-n foo.example` with `dlite install` to adjust the hostname according to your needs.

**Comment by ruimarinho** [comment]
I think the original issues were related to [bonjour](http://www.justincarmony.com/blog/2011/07/27/mac-os-x-lion-etc-hosts-bugs-and-dns-resolution/) and then the shift to ipv6. As far as I remember I had to add two entries to speed up dns resolution - one of local ipv4 and another for ipv6. I'm not sure if this is fixed by now, but I ended up shifting to `.dev`.

**Comment by djui** [comment]
I also can't see how the "issue" (see below) will play a role in this case. The entry is added to `/etc/hosts` which is always prioritized and a constant lookup.

@ruimarinho I think you are referring to the temporary introduction of `discoverd` replacing `mDNSresponder` which caused a lot of trouble but is now fixed: http://www.macrumors.com/2015/05/26/apple-discoveryd-replaced-with-mdnsresponder/

**Comment by djui** [comment]
@nlf regarding "browsers do not understand local.docker": I have a couple of browsers, Chrome and I think Firefox being among them, that interpret and address like `local.docker:8080` as a public valid Internet address and will try to look it up, fail, and then use a Google search on that; which besides being annoying is also a bit risky as I could have testing parameters that would leak information to Google.

I am not sure if this "a me problem" or if all Chrome/Firefox users have this. Adding `http://` in front ensures that the browsers won't try to search for the address but is inconvenient.

**Comment by STRML** [comment]
Just had this bite me as I changed `local.docker` to `docker.local` because I was used to it from previous projects.

According to http://superuser.com/questions/370559/10-second-delay-for-local-tld-in-mac-os-x-lion it appears we can get around this by adding an IPv6 address to /etc/hosts so it doesn't burn anyone else as badly.

**Comment by nlf** [comment]
this is a bit trickier since it means i'll have to make sure the vm actually supports ipv6 thoroughly, and then figure out how to inform the host what the ipv6 address is. and that's assuming that the vmnet framework in osx even plays nicely with ipv6 in the first place.

i'll investigate though, and we'll see.

**Comment by STRML** [comment]
To mitigate the bug, I'm not sure if the address even needs to be right.
Could just be one of those dot decimal addrs. The real point is just to get
osx not to query bonjour.
