### ISSUE TITLE
Why is `sudo` needed?

### ISSUE THREAD

**Issue by activeshadow** [nlf/dlite#40]
Is `sudo` needed solely for the Launchd agent? If so, Homebrew seems to get around this by putting launch scripts in `~/Library/LaunchAgents/`. The `Homebrew Services` tap then recognizes and uses these when providing the `brew service` subcommand.

Perhaps I'm missing some other requirement for `sudo`, such as NFS mounts and modification of `/etc/hosts`?

By the way, I'm _super_ excited about this project... just a little leery of having to use `sudo`. I've been spoiled by Homebrew. I guess it's no worse than having to `eval` stuff from `docker-machine`, though at least I can inspect what I'm about to eval before actually doing so.

**Comment by philipbergen** [comment]
I shouldn't have run it with sudo... Then my machine would likely still be fine...

**Comment by nlf** [comment]
sudo is needed with the install command for creating the sudoers entry.

it's needed for the daemon command (which is run by the launchd plist) in order to create the `/etc/hosts` entry, the nfs export, and also because xhyve itself requires sudo in order to allow networking.

unfortunately, it's not a limitation i can get around just yet.
