### ISSUE TITLE
hello-world not running

### ISSUE THREAD

**Issue by aleemb** [nlf/dlite#46]
I got it running on 10.11.2 El Capitan. However, following along from the hello-world example on the docker website, I can't see hello world.

```
~ $ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b901d36b6f2f: Pull complete 
0a6ba66e537a: Pull complete 
Digest: sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
Status: Downloaded newer image for hello-world:latest
```

Each time I run `docker run hello-world`, I see blank output but containers seem to be created:

```
~ $ docker ps -a
8adbe3dbaa13        hello-world         "/hello"            2 seconds ago       Exited (0) 1 seconds ago                       trusting_engelbart
0f67c3964c3e        hello-world         "/hello"            2 minutes ago       Exited (0) 2 minutes ago                       distracted_jepsen
6daf5a92e745        hello-world         "/hello"            2 minutes ago       Exited (0) 2 minutes ago                       cocky_meitner
```

I cannot start and attach to any of those containers either,

```
~ $ docker attach 8adbe3dbaa13
You cannot attach to a stopped container, start it first
~ $ docker start 8adbe3dbaa13
8adbe3dbaa13
~ $ docker attach 8adbe3dbaa13
You cannot attach to a stopped container, start it first
```

**Comment by nlf** [comment]
try `docker run -it hello-world`, the hello-world container needs an interactive terminal to work correctly

**Comment by clkao** [comment]
I think actually with `docker run -t` it should work, as it isn't requiring stdin and interactivity.  It just requires terminal output.  Can this be reopened?

**Comment by nlf** [comment]
i've actually already added some commits to the master branch that need a little more polish before they get released that address this issue so `docker run hello-world` works without any extra flags.

once i finish cleaning up the last handful of issues with that change, i'll be making a new release

**Comment by mageekguy** [comment]
I'm confirm that allowing `hello-world` to run without `-it` flag is **A VERY GOOD IDEA**.
It's the most easily way to test a fresh install of docker, and if `hello-world` don't run, the user can think that there is a problem somewhere!
In my case, i just spent several hours trying to understand why this container does not work… (and the docker's `-D` flag does not help to understand root cause of the problem).
And it's very difficult to understand this root cause because `/var/run/docker.sock` exists, DhyveOS's VM is up (`ssh docker@local.docker` is ok), `docker version` said that all is ok, all versions are up-to-date, so all is good… but this (fucking) hello-world does not work!
And google was not my friend because i was search informations about `DEBU[0000] Corrupted prefix` according to `docker -D run hello-world`…
I have found this issue because at least i was typed `docker dlite hello-world` in the search box.
However, `dlite` seems to be a great piece of software, thanks @nlf for your job! (have you got any sort of amazon wishlist?)

**Comment by nlf** [comment]
hello-world is working in the version 2 pre-releases without any flags

```
/G/s/gi/n/dlite master ❯ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
03f4658f8b78: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
Status: Downloaded newer image for hello-world:latest

Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/userguide/
```

i don't have an amazon wishlist or anything like that as of now, but thank you for the kind words :)

i have considered adding a link to gratipay somewhere in the readme, but asking for money for something i originally wrote for myself felt a bit greedy so i haven't bothered yet.
