### ISSUE TITLE
create our own ssh key

### ISSUE THREAD

**Issue by nlf** [nlf/dlite#77]
this has come up a few times where people using non-default ssh keys have issues either running the daemon or connecting via ssh. this needs to be debugged and fixed.

edited title: solution will be creating and using our own ssh key, including an entry in `~/.ssh/config`

**Comment by cmosetick** [comment]
@nlf my idea for fixing this issue is to create or append a `~/.ssh/config` file with the correct options for the user in it.

I've been doing the below myself, and it seems to work well for me. Especially because I do not have to remember to type out `docker@` when logging in. I can just type `ssh local.docker` and because of my config file it knows that I mean `docker@local.docker`

I think this method will eliminate the need for a entry in `/etc/hosts` too, based on a small test where I changed the /etc/hosts entry to something bogus. I can still run docker ps and still ssh to the dhyve system because my personal ssh config file is setup correctly.

# Proposal
- create (or append to the existing file) a `~/.ssh/config` file with the following contents as part of the dlite install process.

```
Host local.docker
    HostName 192.168.64.2
    User docker
        # below line is different per whatever the user supplies the installer
        IdentityFile ~/.ssh/docker.key
```

Where docker.key is any standard (e.g. id_rsa.pub) or "non-standard" (e.g. docker.key) key file name that the user might have supplied to the dlite installer.

**Comment by nwillems** [comment]
More related to the installation process, and simplification of the setup.

I would suggest that dlite maintains it's own set of SSH keys and then ask the user to add to the ssh-config.

The following could be done during installation:
Key-generation `$ ssh-keygen -t RSA -b 4096 -f ~/.dlite/id_rsa -N ''`, and config template:

```
Host local.docker
    IdentityFile ~/.dlite/id_rsa
    User docker
```

Then connecting to the xhyve instance would be a simple matter of `$ ssh local.docker`

**Comment by cmosetick** [comment]
@nwillems Your suggestion seems like a good path forward. If I remember correctly even, _cough_, boot2docker did something similar with keys.

However, if you are talking about simplification, it would still be required for the IP address to be included in the `~/.ssh/config` file entry if the dlite `/etc/hosts` append operation is going to be removed from the dlite install process:

```
Host local.docker
    HostName 192.168.64.2  #set to whatever the dlite IP address is
    IdentityFile ~/.dlite/id_rsa
    User docker
```

Without the IP address above, and no hosts file entry, `ssh local.docker` would go no where.

**Comment by nlf** [comment]
The entry in /etc/hosts is going to stay so that exposed ports in docker are reachable from the host without needing the ip. Generating our own ssh key and creating an entry in the ssh config is a good idea though
