### ISSUE TITLE
nfs file watching question

### ISSUE THREAD

**Issue by darrinholst** [nlf/dlite#88]
I'm using nodemon in a project which uses [chokidar](https://github.com/paulmillr/chokidar) internally to pick up file changes. It needs to use polling which works, but my question is about the latency of when file changes are noticed. If I shell into the container and touch a file it picks it up instantly. If I touch a file from the host then it takes a variable amount of time. The gif below shows the behavior. Left side is the log that shows when file changes are noticed, top right is the docker container shell, bottom right is the host system. When I recorded it the the lag wasn't too bad, but I've seen it take upwards of 10 seconds. Any ideas what this could be or any suggestions that I could do to try and track down where it's coming from?

![file watching](https://cloud.githubusercontent.com/assets/4854/12850953/fafabf46-cbec-11e5-8b6c-8dd1807cd06f.gif)

Other than this I'm really digging this solution to docker on osx. :+1:

**Comment by nlf** [comment]
this is just because of nfs, unfortunately. it's a bit slow for changes to show up.

experimental support for virtfs-9p has been added to a fork of xhyve, if either myself or the maintainer of libxhyve manages to get that ported to libxhyve, then i can take advantage of it in DLite and that should be significantly faster. until then, not a whole lot i can do.

**Comment by darrinholst** [comment]
Thanks for the explanation.
