### ISSUE TITLE
docker commands hang

### ISSUE THREAD

**Issue by imsky** [nlf/dlite#95]
`docker ps` and `docker pull` and (I assume) all other docker commands hang, despite the socket file existing. running `dlite rebuild` fixes the issue.

**Comment by kitten** [comment]
Have you tried running `dlite stop; dlite start` and waiting a bit to fix this, instead of rebuilding? That does the trick for me

**Comment by imsky** [comment]
yes that did not help unfortunately, even with waiting a couple of seconds

**Comment by imsky** [comment]
after testing it some more, `dlite stop; dlite start` does in fact work

dlite seems highly unreliable after a restart

closing this issue

**Comment by benjick** [comment]
Having the same issue, how long is a little while?

**Comment by imsky** [comment]
5-10 seconds

**Comment by nlf** [comment]
the issue is likely because when you run `dlite start` the launchctl agent is booting a virtual machine. until that virtual machine is booted, has an ip, and has the docker daemon running - docker commands won't work.

i have an idea for how to address this in a way that will give a clear error message instead of just failing like it currently does
